name: projectx
description: "Tradutor simples que converte sua voz em texto, podendo também ouvir a tradução em outro idiomas"
publish_to: 'none'

version: 0.0.1-alpha+2

environment:
  sdk: '>=3.4.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

# Dynamic Colors
  dynamic_color: ^1.7.0

# Email
  flutter_email_sender: ^6.0.3

# Feedback
  feedback:
      git:
        url: https://github.com/hendrilmendes/feedback.git
        path: feedback
        ref: master

# Flutter TTS
  flutter_tts: ^4.0.2

# Google ML Kit
  google_ml_kit: ^0.18.0

# HTTP  
  http: ^1.2.1

# Intl
  intl: ^0.19.0
  
# Libre Translate  
  libre_translate: ^1.0.0

# Review  
  in_app_review: ^2.0.9

# Package Info
  package_info_plus: ^8.0.0

# Path Provider
  path_provider: ^2.1.3

# Provider
  provider: ^6.1.2

# Shared Preferences
  shared_preferences: ^2.2.3

# Speech to Text
  speech_to_text: ^6.6.2

# Toast
  fluttertoast: ^8.2.6

# Url Launcher
  url_launcher: ^6.3.0

  flutter_localizations:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^4.0.0

flutter:
  generate: true
  uses-material-design: true

  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg


  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
